services:
  backend:
    build:
      context: .
      dockerfile: server/dockerfile
    image: omeshbala/messmind-backend:latest
    ports:
      - "5000:5000"
    env_file:
      - .env

  frontend:
    build: .
    image: omeshbala/messmind-frontend:latest
    ports:
      - "3000:80"
    depends_on:
      - backend