apiVersion: v1
kind: Service
metadata:
  name: messmind-backend-svc
  namespace: {{ .Values.namespace }}
  labels:
    app: messmind
    component: backend
spec:
  selector:
    app: messmind
    component: backend
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.backend.port }}
      targetPort: {{ .Values.service.backend.port }}
  type: {{ .Values.service.backend.type }}
---
apiVersion: v1
kind: Service
metadata:
  name: messmind-frontend-svc
  namespace: {{ .Values.namespace }}
  labels:
    app: messmind
    component: frontend
spec:
  selector:
    app: messmind
    component: frontend
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.frontend.port }}
      targetPort: 80
  type: {{ .Values.service.frontend.type }}
